public enum SoundType
{
    // SHIP
    SHUTDOWN, RESTART,

    SPEEDBOOST, ALARM, SHOOTING, PICKUP,  PROTECTED, DROPMINE,
    
    // LEVEL
    LAPPASSED, VICTORY, LOSS, ACHIEVEMENT,

    // AI
    AIPROJECTILES, AIMINES, AISPEED, AISMOKESCREEN, AIFORCEFIELD,
    AIHOSTILESDETECTED, AIDANGER,
    AISMOKEDEPLOYED, AISYSTEMERROR,
    AICHARGESDRAINED, AICHARGESRESTORED,

    // MENU
    CLICKBUTTON
}